name: Update Pages Index JSON

on:
  push:
    paths:
      - "site/**/*.html" # Trigger when any HTML file in /site is added or modified

jobs:
  update-pages-json:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Run the script to generate pages.json
    - name: Generate pages.json
      run: |
        chmod +x ./scripts/generate_pages_json.sh
        ./scripts/generate_pages_json.sh

    # Step 3: Check if pages.json has changes
    - name: Check for changes
      id: changes
      run: |
        git add ./site/data/pages.json
        git diff --cached --quiet || echo "has_changes=true" >> $GITHUB_ENV

    # Step 4: Commit and push changes (if any)
    - name: Commit and push changes
      if: env.has_changes == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "Update pages.json after new HTML page added"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
