name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Trigger on any push to the main branch
    paths-ignore: # Ignore CSV file updates
      - "data/*.csv"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: . # Deploy the root directory
        publish_branch: gh-pages # The branch used for GitHub Pages
